---
- name: install and configure tomcat 9
  hosts: appserver
  become: yes
  vars_file:
    - defaults.yml
  tasks:
    - name: update packages and install java
      apt:
        name: "{{ java_package }}"
        update_cache: yes
        state: present
    - name: add a tomcat user
      ansible.builtin.user:
        name: "{{ tomcat_username }}"
        home: "{{ tomcat_home }}"
        shell: "{{ tomcat_shell }}"
        state: present
    - name: download the tomcat distributor
      get_url:
        url: "https://archive.apache.org/dist/tomcat/tomcat-9/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz"
        dest: "/tmp/apache-tomcat-{{ tomcat_version }}.tar.gz"
        notify : Untar the file
  handlers:
    - name: Untar the file
        unarchive:
          src: "/tmp/apache-tomcat-{{ tomcat_version }}.tar.gz"
          dest: "{{ tomcat_home }}"
    - name: create a symlink
        ansible.builtin.file:
          src: "{{ tomcat_home }}/apache-tomcat-{{ tomcat_version }}"
          dest: "{{ tomcat_home }}/latest"
          state: link
    - name : give ownership to tomcat user & group
        ansible.builtin.file:
          path: "{{ tomcat_home }}"
          state: directory
          recurse: yes
          owner: "{{ tomcat_username }}"
          group: "{{ tomcat_username }}"
    - name: find all the shell files in the binaries
      find:
        path: "{{ tomcat_home }}/latest/bin"
        pattern: "*.sh"
      register: shfiles
    - set_fact:
        tomcat_executables: "{{ shfiles.files | map(attribute='path') |list }}"
    - name: change permission of shell files
      file:
        path: "{{ item }}"
        mode: 0751
      with_items: "{{ tomcat_executables }}"
    - name: create tomcat service file
      ansible.builtin.copy:
        src: tomcat.service
        dest: "{{ tomcat_servive_dest }}"
      notify: reload enable and start tomcat
    - name: ensure tomcat is running
      ansible.builtin.systemd:
        name: tomcat.service
        state: started 
  handler:
    - name: reload enable and start tomcat
      ansible.builtin.systemd:
        name: tomcat.service
        daemon_reload: yes
        enabled: yes
        state: reloaded  
        

